name: PREPROD Praticboutic javabackend Workflow
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'  # adapte si besoin

    - name: Connexion SSH et dÃ©ploiement
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.FTP_JAVABACKENDSERVER }}
        username: ${{ secrets.FTP_JAVABACKENDUSERNAME }}
        key: ${{ secrets.FTP_JAVABACKENDSSH_KEY }}
        port: 22
        script: |
          # ðŸ›‘ Ã‰tape 1 : tuer tout processus Java Ã©coutant sur le port 8444
          PID=$(lsof -i :8082 -sTCP:LISTEN -t) && if [ -n "$PID" ]; then
          echo "Processus Java trouvÃ© sur le port 8082 (PID: $PID), arrÃªt en cours..."
          kill "$PID"
          sleep 2
          if ps -p "$PID" > /dev/null; then
            echo "ForÃ§age du processus (kill -9)..."
            kill -9 "$PID"
          fi
          else
            echo "Aucun processus Java sur le port 8082."
          fi
          shopt -s extglob dotglob
          rm -rf /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/
          # git pull origin main  # ou "master" selon ta branche
          git clone git@github.com:praticboutic/praticboutic-backend.git /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/
          
          cd /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/src/main/resources/
          cp application-preprod.properties application.properties

          cd /var/www/vhosts/praticboutic.fr/
          chown -R qruser:psaserv preback.praticboutic.fr/
          chmod -R 777 preback.praticboutic.fr/

          cd /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/
          # Stop l'app, nettoie, build avec le profil prod
          sudo -u qruser mvn clean install -Dmaven.test.skip=true -Dspring-boot.run.profiles=preprod

          # Trouve le fichier JAR
          JAR_FILE=$(find /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/target -name 'praticboutic-backend-springboot-*.jar' ! -name '*.original' | head -n 1)
          
          PID=$(lsof -i :8082 -sTCP:LISTEN -t)
          if [ -n "$PID" ]; then
            echo "ArrÃªt du processus Java sur le port 8082 (PID: $PID)"
            kill "$PID" || kill -9 "$PID"
          fi
          
          # DÃ©marre la nouvelle version en arriÃ¨re-plan
          sudo -u qruser nohup java -jar "$JAR_FILE" --spring.profiles.active=preprod > /var/www/vhosts/praticboutic.fr/preback.praticboutic.fr/springboot/log.out 2>&1 &
          chown qruser:psaserv log.out

        
            
